### ISSUE TITLE
Use assume role

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [Andrew-Chen-Wang/cookiecutter-django-ec2-github#16]
Much easier, more secure

```
    - name: Configure AWS credentials
      # Visit https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
      # to learn how to set this up
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::1234567890:role/role-name
        aws-region: us-east-1
```

To make it work properly:
- https://github.com/aws-actions/configure-aws-credentials/issues/318

- https://github.com/github/docs/pull/18550

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::1234567890:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "ForAllValues:StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
                    "token.actions.githubusercontent.com:iss": "https://token.actions.githubusercontent.com"
                    "token.actions.githubusercontent.com:sub": "repo:Org-Case-Sensitive/rEpo:ref:refs/heads/main"
                }
            }
        }
    ]
}
```
